CREATE TABLE "usuarios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usuarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"barrio_id" integer NOT NULL,
	"nombre" varchar NOT NULL,
	"usuario" varchar NOT NULL,
	"contrasena_hash" varchar NOT NULL,
	"rol" varchar DEFAULT 'Vecino',
	"fecha_registro" timestamp DEFAULT now(),
	CONSTRAINT "usuarios_usuario_unique" UNIQUE("usuario")
);
--> statement-breakpoint
CREATE TABLE "comites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"barrio_id" integer NOT NULL,
	"fecha_creacion" timestamp DEFAULT now(),
	CONSTRAINT "comites_barrio_id_unique" UNIQUE("barrio_id")
);
--> statement-breakpoint
CREATE TABLE "miembros_comite" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "miembros_comite_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"comite_id" integer NOT NULL,
	"usuario_id" integer NOT NULL,
	"rol" varchar NOT NULL,
	"fecha_registro" timestamp DEFAULT now(),
	CONSTRAINT "miembros_comite_usuario_id_unique" UNIQUE("usuario_id")
);
--> statement-breakpoint
CREATE TABLE "apoyos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "apoyos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"usuario_id" integer NOT NULL,
	"reporte_id" integer NOT NULL,
	"fecha" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "comentarios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comentarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"reporte_id" integer NOT NULL,
	"usuario_id" integer NOT NULL,
	"mensaje" text NOT NULL,
	"activo" boolean DEFAULT true,
	"fecha_creacion" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "gestiones_directiva" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gestiones_directiva_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"reporte_id" integer NOT NULL,
	"lider_id" integer NOT NULL,
	"estado_asignado" varchar NOT NULL,
	"mensaje" text NOT NULL,
	"fecha_gestion" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "reportes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reportes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"usuario_id" integer NOT NULL,
	"barrio_id" integer NOT NULL,
	"direccion" varchar NOT NULL,
	"ubicacion" varchar NOT NULL,
	"foto_url" varchar NOT NULL,
	"estado" varchar DEFAULT 'Pendiente',
	"descripcion" text NOT NULL,
	"activo" boolean DEFAULT true,
	"fecha_creacion" timestamp DEFAULT now(),
	"fecha_actualizacion" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "barrios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "barrios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ciudad_id" integer NOT NULL,
	"nombre" varchar NOT NULL,
	"fecha_creacion" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ciudades" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ciudades_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provincia_id" integer NOT NULL,
	"nombre" varchar NOT NULL,
	"fecha_creacion" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "provincias" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provincias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar NOT NULL,
	"fecha_creacion" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_barrio_id_barrios_id_fk" FOREIGN KEY ("barrio_id") REFERENCES "public"."barrios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comites" ADD CONSTRAINT "comites_barrio_id_barrios_id_fk" FOREIGN KEY ("barrio_id") REFERENCES "public"."barrios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "miembros_comite" ADD CONSTRAINT "miembros_comite_comite_id_comites_id_fk" FOREIGN KEY ("comite_id") REFERENCES "public"."comites"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "miembros_comite" ADD CONSTRAINT "miembros_comite_usuario_id_usuarios_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "apoyos" ADD CONSTRAINT "apoyos_usuario_id_usuarios_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "apoyos" ADD CONSTRAINT "apoyos_reporte_id_reportes_id_fk" FOREIGN KEY ("reporte_id") REFERENCES "public"."reportes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comentarios" ADD CONSTRAINT "comentarios_reporte_id_reportes_id_fk" FOREIGN KEY ("reporte_id") REFERENCES "public"."reportes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comentarios" ADD CONSTRAINT "comentarios_usuario_id_usuarios_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gestiones_directiva" ADD CONSTRAINT "gestiones_directiva_reporte_id_reportes_id_fk" FOREIGN KEY ("reporte_id") REFERENCES "public"."reportes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gestiones_directiva" ADD CONSTRAINT "gestiones_directiva_lider_id_usuarios_id_fk" FOREIGN KEY ("lider_id") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reportes" ADD CONSTRAINT "reportes_usuario_id_usuarios_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reportes" ADD CONSTRAINT "reportes_barrio_id_barrios_id_fk" FOREIGN KEY ("barrio_id") REFERENCES "public"."barrios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "barrios" ADD CONSTRAINT "barrios_ciudad_id_ciudades_id_fk" FOREIGN KEY ("ciudad_id") REFERENCES "public"."ciudades"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ciudades" ADD CONSTRAINT "ciudades_provincia_id_provincias_id_fk" FOREIGN KEY ("provincia_id") REFERENCES "public"."provincias"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "apoyos_usuario_id_reporte_id_idx" ON "apoyos" USING btree ("usuario_id","reporte_id");