CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "barrio_id" integer NOT NULL,
  "nombre" varchar NOT NULL,
  "usuario" varchar UNIQUE NOT NULL,
  "contrasena_hash" varchar NOT NULL,
  "rol_id" integer NOT NULL,
  "fecha_registro" timestamp DEFAULT (now())
);

CREATE TABLE "comites" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "barrio_id" integer UNIQUE NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE TABLE "miembros_comite" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "comite_id" integer NOT NULL,
  "usuario_id" integer UNIQUE NOT NULL,
  "rol" varchar NOT NULL,
  "fecha_registro" timestamp DEFAULT (now())
);

CREATE TABLE "apoyos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "reporte_id" integer NOT NULL,
  "fecha" timestamp DEFAULT (now())
);

CREATE TABLE "comentarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporte_id" integer NOT NULL,
  "usuario_id" integer NOT NULL,
  "mensaje" text NOT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE TABLE "gestiones_directiva" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporte_id" integer NOT NULL,
  "lider_id" integer NOT NULL,
  "estado_assigned" varchar NOT NULL,
  "mensaje" text NOT NULL,
  "fecha_gestion" timestamp DEFAULT (now())
);

CREATE TABLE "reportes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "barrio_id" integer NOT NULL,
  "direccion" varchar NOT NULL,
  "ubicacion" varchar NOT NULL,
  "foto_url" varchar NOT NULL,
  "estado" varchar DEFAULT 'Pendiente',
  "descripcion" text NOT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (now()),
  "fecha_actualizacion" timestamp DEFAULT (now())
);

CREATE TABLE "barrios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ciudad_id" integer NOT NULL,
  "nombre" varchar NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE TABLE "ciudades" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "provincia_id" integer NOT NULL,
  "nombre" varchar NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE TABLE "provincias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX "apoyos_usuario_id_reporte_id_idx" ON "apoyos" ("usuario_id", "reporte_id");

ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios" ADD FOREIGN KEY ("barrio_id") REFERENCES "barrios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "barrios" ADD FOREIGN KEY ("id") REFERENCES "comites" ("barrio_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "miembros_comite" ADD FOREIGN KEY ("comite_id") REFERENCES "comites" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios" ADD FOREIGN KEY ("id") REFERENCES "miembros_comite" ("usuario_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "apoyos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "apoyos" ADD FOREIGN KEY ("reporte_id") REFERENCES "reportes" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comentarios" ADD FOREIGN KEY ("reporte_id") REFERENCES "reportes" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comentarios" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gestiones_directiva" ADD FOREIGN KEY ("reporte_id") REFERENCES "reportes" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gestiones_directiva" ADD FOREIGN KEY ("lider_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reportes" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reportes" ADD FOREIGN KEY ("barrio_id") REFERENCES "barrios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "barrios" ADD FOREIGN KEY ("ciudad_id") REFERENCES "ciudades" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ciudades" ADD FOREIGN KEY ("provincia_id") REFERENCES "provincias" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;