CREATE TABLE provincias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR NOT NULL,
  fecha_creacion TIMESTAMP DEFAULT NOW()
);

CREATE TABLE ciudades (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provincia_id INT NOT NULL,
  nombre VARCHAR NOT NULL,
  fecha_creacion TIMESTAMP DEFAULT NOW()
);

CREATE TABLE barrios (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ciudad_id INT NOT NULL,
  nombre VARCHAR NOT NULL,
  fecha_creacion TIMESTAMP DEFAULT NOW()
);

CREATE TABLE usuarios (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barrio_id INT NOT NULL,
  nombre VARCHAR NOT NULL,
  usuario VARCHAR UNIQUE NOT NULL,
  contrasena_hash VARCHAR NOT NULL,
  rol VARCHAR DEFAULT 'Vecino',
  fecha_registro TIMESTAMP DEFAULT NOW()
);

CREATE TABLE reportes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INT NOT NULL,
  barrio_id INT NOT NULL,
  direccion VARCHAR NOT NULL,
  ubicacion VARCHAR NOT NULL,
  foto_url VARCHAR NOT NULL,
  estado VARCHAR DEFAULT 'Pendiente',
  descripcion TEXT NOT NULL,
  activo BOOLEAN DEFAULT true,
  fecha_creacion TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP DEFAULT NOW()
);

CREATE TABLE gestiones_directiva (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporte_id INT NOT NULL,
  lider_id INT NOT NULL,
  estado_asignado VARCHAR NOT NULL,
  mensaje TEXT NOT NULL,
  fecha_gestion TIMESTAMP DEFAULT NOW()
);

CREATE TABLE comentarios (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporte_id INT NOT NULL,
  usuario_id INT NOT NULL,
  mensaje TEXT NOT NULL,
  activo BOOLEAN DEFAULT true,
  fecha_creacion TIMESTAMP DEFAULT NOW()
);

CREATE TABLE apoyos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INT NOT NULL,
  reporte_id INT NOT NULL,
  fecha TIMESTAMP DEFAULT NOW()
);

CREATE UNIQUE INDEX ON apoyos (usuario_id, reporte_id);

COMMENT ON COLUMN reportes.usuario_id IS 'Vecino que reporta la incidencia inicial';
COMMENT ON COLUMN reportes.barrio_id IS 'Tablón territorial donde se visualizará el daño';
COMMENT ON COLUMN reportes.ubicacion IS 'Coordenadas X/Y en el mapa';
COMMENT ON COLUMN reportes.estado IS 'Estado actual para consultas rápidas';
COMMENT ON COLUMN reportes.activo IS 'Borrado lógico';

COMMENT ON COLUMN gestiones_directiva.reporte_id IS 'El reporte que se está gestionando';
COMMENT ON COLUMN gestiones_directiva.lider_id IS 'El líder específico que emite esta respuesta';
COMMENT ON COLUMN gestiones_directiva.estado_asignado IS 'El estado que se definió en este paso (ej. En_proceso)';
COMMENT ON COLUMN gestiones_directiva.mensaje IS 'La respuesta o actualización oficial';

ALTER TABLE ciudades ADD FOREIGN KEY (provincia_id) REFERENCES provincias (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE barrios ADD FOREIGN KEY (ciudad_id) REFERENCES ciudades (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE usuarios ADD FOREIGN KEY (barrio_id) REFERENCES barrios (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reportes ADD FOREIGN KEY (barrio_id) REFERENCES barrios (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reportes ADD FOREIGN KEY (usuario_id) REFERENCES usuarios (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE apoyos ADD FOREIGN KEY (usuario_id) REFERENCES usuarios (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE apoyos ADD FOREIGN KEY (reporte_id) REFERENCES reportes (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE comentarios ADD FOREIGN KEY (reporte_id) REFERENCES reportes (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE comentarios ADD FOREIGN KEY (usuario_id) REFERENCES usuarios (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE gestiones_directiva ADD FOREIGN KEY (reporte_id) REFERENCES reportes (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE gestiones_directiva ADD FOREIGN KEY (lider_id) REFERENCES usuarios (id) DEFERRABLE INITIALLY IMMEDIATE;
