/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Permite a los usuarios del sistema iniciar sesión y obtener un token JWT firmado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        usuario: string;
                        contrasena: string;
                    };
                };
            };
            responses: {
                /** @description Autenticación exitosa. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description El payload enviado no cumple con las validaciones requeridas. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description El nombre de usuario o la contraseña son incorrectos. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar usuario
         * @description Permite registrar un nuevo usuario en la plataforma con el rol de ciudadano.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        nombre: string;
                        usuario: string;
                        contrasena: string;
                        barrioId: number;
                    };
                };
            };
            responses: {
                /** @description Usuario registrado exitosamente. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterUserResponse"];
                    };
                };
                /** @description El payload enviado no cumple con las validaciones requeridas. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Barrio no encontrado. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflicto: El nombre de usuario ya está en uso. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener perfil del usuario
         * @description Recupera el perfil del usuario autenticado que emite la solicitud.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Perfil de usuario recuperado exitosamente. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Usuario no encontrado. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register-leader": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar líder y fundar comité
         * @description Permite fundar un comité barrial y dar de alta a su líder de forma pública en un solo paso.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        nombre: string;
                        usuario: string;
                        contrasena: string;
                        barrioId: number;
                    };
                };
            };
            responses: {
                /** @description Comité barrial y líder registrados exitosamente. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterCommitteeResponse"];
                    };
                };
                /** @description El payload enviado no cumple con las validaciones requeridas. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Barrio no encontrado. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflicto por duplicidad de usuario o de comité en el barrio. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territory/province": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener todas las provincias
         * @description Recupera la lista completa de provincias registradas en el sistema para su uso en formularios de registro.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catálogo de provincias recuperado con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProvincesResponse"];
                    };
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territory/city": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener ciudades por provincia
         * @description Recupera las ciudades asociadas a una provincia específica mediante su ID.
         */
        get: {
            parameters: {
                query: {
                    provinceId: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ciudades recuperadas con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CitiesResponse"];
                    };
                };
                /** @description El ID de la provincia proporcionado es inválido. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Provincia no encontrada. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/territory/neighborhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener barrios por ciudad
         * @description Recupera los barrios asociados a una ciudad específica mediante su ID.
         */
        get: {
            parameters: {
                query: {
                    cityId: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Barrios recuperados con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodsResponse"];
                    };
                };
                /** @description El ID de la ciudad proporcionado es inválido. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Ciudad no encontrada. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/committee/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar miembro del comité
         * @description Permite a un líder de comité barrial registrar nuevos miembros directivos (Secretario, Vocal).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        usuarioId: number;
                        /** @enum {string} */
                        rolComite: "Secretario" | "Vocal";
                    };
                };
            };
            responses: {
                /** @description Miembro del comité registrado exitosamente. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterCommitteeMemberResponse"];
                    };
                };
                /** @description El payload enviado no cumple con las validaciones requeridas. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Acceso denegado. Solo los líderes pueden realizar esta operación. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Comité no encontrado para el barrio del líder. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflicto: El nombre de usuario ya está en uso. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor o configuración de seguridad. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener vecinos elegibles del barrio
         * @description Recupera la lista de vecinos (ciudadanos regulares) del mismo barrio que el líder o miembro solicitante para poder ser asignados al comité.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vecinos del barrio recuperados exitosamente. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborsResponse"];
                    };
                };
                /** @description El usuario solicitante no pertenece a ningún barrio. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Acceso denegado. Solo líderes y miembros pueden acceder. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/committee/members/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener miembros del comité
         * @description Recupera la lista completa de los miembros directivos (Presidente, Secretario, Vocal) del comité del barrio del usuario autenticado.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Miembros del comité recuperados con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommitteeMembersListResponse"];
                    };
                };
                /** @description El usuario solicitante no pertenece a ningún barrio. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Acceso denegado. Solo líderes y miembros pueden acceder. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Comité no encontrado para el barrio del usuario. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener firma para subida directa de imágenes
         * @description Genera una firma criptográfica para permitir al frontend subir imágenes directamente a Cloudinary.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Carpeta de destino en Cloudinary */
                    folder?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Firma de Cloudinary generada con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StorageSignatureResponse"];
                    };
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear reporte de incidencia
         * @description Permite registrar un reporte de incidencia ciudadana en el barrio del usuario autenticado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        direccion: string;
                        ubicacion: string;
                        /** Format: uri */
                        fotoUrl: string;
                        descripcion: string;
                    };
                };
            };
            responses: {
                /** @description Reporte de incidencia registrado exitosamente. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateReportResponse"];
                    };
                };
                /** @description El payload enviado contiene errores de validación. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar reportes activos del barrio
         * @description Recupera los reportes barriales activos ('pendiente' o 'en_gestion') para el barrio del usuario autenticado (cualquier rol).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Listado de reportes activos recuperado con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListActiveReportsResponse"];
                    };
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{id}/supports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener estadísticas de apoyos de un reporte
         * @description Recupera la cantidad total de apoyos y si el usuario autenticado lo ha apoyado.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estadísticas de apoyos recuperadas con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupportStatsResponse"];
                    };
                };
                /** @description ID de reporte inválido o erróneo. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reporte no encontrado en el sistema. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Alternar apoyo a reporte (Corazón)
         * @description Registra o elimina un apoyo (like) en el reporte especificado por ID para el usuario autenticado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Apoyo alternado con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToggleSupportResponse"];
                    };
                };
                /** @description ID de reporte inválido o erróneo. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reporte no encontrado en el sistema. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener comentarios de un reporte
         * @description Recupera la lista de comentarios de un reporte de incidencia específico. Solo accesible para líderes y miembros.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Listado de comentarios recuperado con éxito. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListCommentsResponse"];
                    };
                };
                /** @description ID de reporte inválido. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Acceso denegado. Solo líderes y miembros pueden acceder. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reporte no encontrado en el sistema. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Registrar comentario en reporte
         * @description Registra un comentario en el reporte especificado por ID para el usuario autenticado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        mensaje: string;
                    };
                };
            };
            responses: {
                /** @description Comentario registrado con éxito. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateCommentResponse"];
                    };
                };
                /** @description Payload o ID de reporte inválido. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No autorizado o token JWT inválido. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reporte no encontrado en el sistema. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error interno del servidor. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginResponse: {
            message: string;
            data: {
                token: string;
            };
        };
        MeResponse: {
            message: string;
            data: {
                id: number;
                nombre: string;
                usuario: string;
                rol: string;
                barrioId: number | null;
            };
        };
        RegisterCommitteeResponse: {
            message: string;
            data: {
                comiteId: number;
                usuarioId: number;
                miembroId: number;
            };
        };
        RegisterCommitteeMemberResponse: {
            message: string;
            data: {
                miembroId: number;
            };
        };
        CommitteeMembersListResponse: {
            message: string;
            data: {
                id: number;
                usuarioId: number;
                nombre: string;
                usuario: string;
                /** @enum {string} */
                rol: "Presidente" | "Secretario" | "Vocal";
                fechaRegistro?: string | null;
            }[];
        };
        RegisterUserResponse: {
            message: string;
            data: {
                id: number;
                nombre: string;
                usuario: string;
                rol: string;
                barrioId: number;
                fechaRegistro?: string;
            };
        };
        ProvincesResponse: {
            message: string;
            data: {
                id: number;
                nombre: string;
                /** Format: date-time */
                fechaCreacion?: string;
            }[];
        };
        CitiesResponse: {
            message: string;
            data: {
                id: number;
                provinciaId: number;
                nombre: string;
                /** Format: date-time */
                fechaCreacion?: string;
            }[];
        };
        NeighborhoodsResponse: {
            message: string;
            data: {
                id: number;
                ciudadId: number;
                nombre: string;
                /** Format: date-time */
                fechaCreacion?: string;
            }[];
        };
        NeighborsResponse: {
            message: string;
            data: {
                id: number;
                nombre: string;
                usuario: string;
                fechaRegistro?: string;
            }[];
        };
        StorageSignatureResponse: {
            message: string;
            data: {
                signature: string;
                timestamp: number;
                folder: string;
                apiKey: string;
                cloudName: string;
            };
        };
        CreateReportResponse: {
            message: string;
            data: {
                id: number;
                usuarioId: number;
                barrioId: number;
                direccion: string;
                ubicacion: string;
                fotoUrl: string;
                estado: string;
                descripcion: string;
                fechaCreacion?: string;
            };
        };
        ListActiveReportsResponse: {
            message: string;
            data: {
                id: number;
                usuarioId: number;
                barrioId: number;
                direccion: string;
                ubicacion: string;
                fotoUrl: string;
                estado: string;
                descripcion: string;
                fechaCreacion?: string;
                fechaActualizacion?: string;
            }[];
        };
        ToggleSupportResponse: {
            message: string;
            data: {
                supported: boolean;
            };
        };
        SupportStatsResponse: {
            message: string;
            data: {
                count: number;
                hasSupported: boolean;
            };
        };
        CreateCommentResponse: {
            message: string;
            data: {
                id: number;
                reporteId: number;
                usuarioId: number;
                mensaje: string;
                fechaCreacion?: string;
            };
        };
        ListCommentsResponse: {
            message: string;
            data: {
                id: number;
                reporteId: number;
                usuarioId: number;
                mensaje: string;
                fechaCreacion?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
